name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    env:
      ENV_NAME: linting
      PYTHON: 3.8
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 1
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Environment
        run: |
          pip install pre-commit
      - name: Linting
        run: |
          pre-commit install
          pre-commit run -a
  datacache:
    name: Cache Data (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: cache-kernels
        id: cache-kernels
        uses: actions/cache@v3
        with:
          path: lunarsky/data/spk/planets/de430.bsp
          key: kernel-de430-${{ runner.os }}
      - name: Download kernels
        if: steps.cache-kernels.outputs.cache-hit != 'true'
        run: |
          pip install -e .
          python -c "from lunarsky.spice_utils import download_big_kernels; download_big_kernels()"

  tests:
    env:
      ENV_NAME: tests
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    needs: [datacache, linter]
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: load-cache
        uses: actions/cache@v3
        with:
          path: lunarsky/data/spk/planets/de430.bsp
          key: kernel-de430-${{ runner.os }}
      - name: Install
        run: |
          pip install .[test] pytest-cov
      - name: Run Tests
        run: |
          python -m pytest --cov=lunarsky --cov-config=.coveragerc --cov-report xml:./coverage.xml --junitxml=test-reports/xunit.xml
      - uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest' && success()
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          file: ./coverage.xml #optional
